#spring:
#  jpa:
#    show-sql: true
#    database: POSTGRESQL
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        show_sql: false
#        generate_statistics: false
#  datasource:
#    url: jdbc:postgresql://localhost:5432/stockoverview
#    username: postgres
#    password: root
#    driverClassName: org.postgresql.Driver
#  sql:
#    init:
#      platform: postgres
#client:
#  someapi:
#    url: http://jsonplaceholder.typicode.com
#jwt:
#  secret: some_secret
#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace